-- ======================================================
-- SUPPLIER ANALYSIS
-- ======================================================

-- 1. Total Suppliers
SELECT COUNT(DISTINCT SupplierID) AS Total_Suppliers
FROM supply_chain;

-- 2. Orders Handled by Each Supplier
SELECT SupplierName,
COUNT(OrderID) AS Total_Orders
FROM supply_chain
GROUP BY SupplierName
ORDER BY Total_Orders DESC;

-- 3. Revenue Generated by Each Supplier
SELECT SupplierName,
SUM(TotalCost) AS Revenue
FROM supply_chain
GROUP BY SupplierName
ORDER BY Revenue DESC;

-- 4. Average Supplier Rating
SELECT SupplierName,
ROUND(AVG(SupplierRating),2) AS Average_Rating
FROM supply_chain
GROUP BY SupplierName
ORDER BY Average_Rating DESC;

-- 5. Best Rated Suppliers
SELECT SupplierName,
SupplierRating
FROM supply_chain
ORDER BY SupplierRating DESC
LIMIT 10;

-- 6. Lowest Rated Suppliers
SELECT SupplierName,
SupplierRating
FROM supply_chain
ORDER BY SupplierRating ASC
LIMIT 10;

-- 7. Average Lead Time by Supplier
SELECT SupplierName,
ROUND(AVG(LeadTimeDays),2) AS Average_Lead_Time
FROM supply_chain
GROUP BY SupplierName
ORDER BY Average_Lead_Time ASC;

-- 8. Average Delay by Supplier
SELECT SupplierName,
ROUND(AVG(DelayDays),2) AS Average_Delay
FROM supply_chain
GROUP BY SupplierName
ORDER BY Average_Delay DESC;

-- 9. Supplier-wise Defective Units
SELECT SupplierName,
SUM(DefectiveUnits) AS Total_Defective
FROM supply_chain
GROUP BY SupplierName
ORDER BY Total_Defective DESC;

-- 10. Average Return Rate by Supplier
SELECT SupplierName,
ROUND(AVG(ReturnRate),2) AS Average_Return_Rate
FROM supply_chain
GROUP BY SupplierName
ORDER BY Average_Return_Rate DESC;

-- 11. Suppliers by Country
SELECT SupplierCountry,
COUNT(DISTINCT SupplierID) AS Total_Suppliers
FROM supply_chain
GROUP BY SupplierCountry
ORDER BY Total_Suppliers DESC;

-- 12. Revenue by Supplier Country
SELECT SupplierCountry,
SUM(TotalCost) AS Revenue
FROM supply_chain
GROUP BY SupplierCountry
ORDER BY Revenue DESC;

-- 13. Orders by Supplier Country
SELECT SupplierCountry,
COUNT(OrderID) AS Orders
FROM supply_chain
GROUP BY SupplierCountry
ORDER BY Orders DESC;

-- 14. Supplier Performance Summary
SELECT SupplierName,
AVG(SupplierRating) AS Avg_Rating,
AVG(LeadTimeDays) AS Avg_Lead_Time,
AVG(DelayDays) AS Avg_Delay,
SUM(DefectiveUnits) AS Total_Defects
FROM supply_chain
GROUP BY SupplierName
ORDER BY Avg_Rating DESC;

-- 15. Top 5 Suppliers by Revenue
SELECT SupplierName,
SUM(TotalCost) AS Revenue
FROM supply_chain
GROUP BY SupplierName
ORDER BY Revenue DESC
LIMIT 5;

-- 16. Bottom 5 Suppliers by Revenue
SELECT SupplierName,
SUM(TotalCost) AS Revenue
FROM supply_chain
GROUP BY SupplierName
ORDER BY Revenue ASC
LIMIT 5;

-- 17. Suppliers with High Delays (>5 Days Average)
SELECT SupplierName,
ROUND(AVG(DelayDays),2) AS Avg_Delay
FROM supply_chain
GROUP BY SupplierName
HAVING Avg_Delay > 5
ORDER BY Avg_Delay DESC;

-- 18. Suppliers with High Return Rate
SELECT SupplierName,
ROUND(AVG(ReturnRate),2) AS Avg_Return_Rate
FROM supply_chain
GROUP BY SupplierName
ORDER BY Avg_Return_Rate DESC;

-- 19. Suppliers with Most Orders
SELECT SupplierName,
COUNT(*) AS Orders
FROM supply_chain
GROUP BY SupplierName
ORDER BY Orders DESC
LIMIT 10;

-- 20. Supplier Overall Score
SELECT SupplierName,
AVG(SupplierRating) AS Rating,
AVG(LeadTimeDays) AS Lead_Time,
AVG(DelayDays) AS Delay_Time,
AVG(ReturnRate) AS Return_Rate
FROM supply_chain
GROUP BY SupplierName
ORDER BY Rating DESC;
